name: build-push
on:
  push:
  workflow_dispatch:

jobs:
  base:
    strategy:
      fail-fast: false
      matrix:
        dir:
          - base
          - vault
    uses: libops/.github/.github/workflows/build-push.yaml@d7f0ba06b4c8a1f8559892ea65a0b1af4d024dd3 # main
    with:
      image: ${{ matrix.dir }}
      context: ${{ matrix.dir }}
    permissions:
      contents: read
      packages: write
    secrets: inherit
